-- auto Generated on 2019-07-20
-- DROP TABLE IF EXISTS user_red_packet;
CREATE TABLE user_red_packet(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	red_packet_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT 'redPacketId',
	user_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT 'userId',
	amount DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT 'amount',
	grab_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'grabTime',
	note VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'note',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user_red_packet';
